### PR TITLE
Add profiles for complete coverage

### PR DESCRIPTION
**Pull request by tresoldi**
This PR expands on the profiles first started by @natalia-morozova , for full coverage (~65k lexemes, 41 languages, ~360k tokens, 738 segments).

The 41 profiles are in `etc/orthography` and the code uses the multiprofiles implemented by @xrotwang ( https://github.com/lexibank/pylexibank/pull/152/ ). The profiles are also sorted and organized with the tool I proposed a couple of weeks ago ( https://github.com/tresoldi/lexibanktools , whose integration to `pylexibank` I postponed because I wanted to refine it with this tour-de-force of WOLD).

For some reason which I was not able to debug, neither the `form_spec` nor the `lexemes.csv` are being applied, even though they are loaded. I am currently doing it manually; if someone can immediately tell what I am doing wrong (probably something very stupid), just let me know, otherwise I will investigate before merging. Note that we cannot split over slashes, as in a number of languages they are graphemes.

As for the profiles themselves, they would benefit from a manual revision, which I'd carry after your review and after merging. I also plan to finish the module for removing superfluous profile rules (i.e., those where `ab` is equal to `a + b`) -- this does not change the results, but will be important for the third module, the one for suggesting orthographic mapping based in previous examples.

In terms of phonology, one thing worth discussing is whether we should keep diphthongs as they are or if they should be separated. They are only found in some of the profiles, notably English and Dutch (derived from CELEX), and I would be in favor of doing so.

### CODE REVIEW

**Review by LinguList — APPROVED** [review]
I think it is because you add the form directly, and if you add a form, it is not passed to the formspec, since the formspec is applied to values. So if you change this to "add_forms_from_XXX", it should capture it. But I am fine with approving this now, so we can then have another pass without all the profiles...

**Comment by tresoldi** [comment]
Of course! I'll work on it later, thanks @LinguList !

**Comment by tresoldi** [comment]
Great, the last commit uses `.add_forms_from_value()` and everything in the code seems to be in order.

I had to extend `lexemes.csv` because of the issue of the slash used as a grapheme in some of the languages (we don't have a per-doculect form-spec, and honestly it is better to keep it that way). At least I could incorporate a dozen more synonyms that were left out it the earlier commit, so that now all the synonyms in the original data have, as far I can tell, a segment version.

**Comment by SimonGreenhill** [comment]
Looks good to me, agree with merging now and then doing a manual round as you both suggest. Thanks!

**Review by SimonGreenhill — APPROVED** [review]

**Pull request merged**
