### PR TITLE
modify WhiteHmong orthography

### PR DESCRIPTION
**Pull request by Wu-Urbanek**
I added the morpheme segmentations and modified some tonal markers in the White Hmong data.

### CODE REVIEW

**Review by LinguList — CHANGES_REQUESTED** [review]
WhiteHmong ortho profile:

Lines 38ff (grapheme "c"): this should be rendered as tɕ, nc should be rendered as dʑ, as this is the standard orthography they also use in Chen, right?

Please check also with the description in Ratliff at wold: https://wold.clld.org/vocabulary/25 (there is a tab with explanations).

This says: 

tx -> ts
ts -> tʃ

vowels that appear twice, like oo are o + ŋ not õ

dipthongs like ia ie should be written as:

ia -> i/j a
ie -> i/j e
ua -> u/w a

All cases of `n` + stop render the stop as voiced, which is wrong, at least, I could not find this in the description, it is by no means mentioned, and we don't find it in Chen's transcriptions neither. 

So in brief: there is quite something to modify here, and it would be good, @macyl, if you could compare the sounds with the White Hmong in Ratliff, particular words, etc., to show how this would be rendered in her version. Please do not run the linter on all orthography profiles again: this makes this PR almost unreadable, only change the orthography file for the time being.

**Comment by xrotwang** [comment]
It's a bit unfortunate that basically all profiles changed significantly - at least looking at the diffs - in a PR titled "modify White Hmong orthography". Can we isolate the actual changes? Or do we need to infer these from the changes in `forms.csv`?

**Comment by LinguList** [comment]
Yes, @xrotwang, I think, @MacyL applied the linter, which was not used before.

**Comment by LinguList** [comment]
So it re-sorts all orthography files, etc. But this would hopefully be the last time, as it is only one time that it sorts this. @MacyL, for the future, please be more careful in how much you change, okay? (I made the same error often in the past)

In fact, we can close this PR, and then ONLY push the orthography profile for WhiteHmong. No pushing to the cldf/ folder, etc.

I just checked Ratliff2010 on HmongDaw, and it is important to note that you have to closely compare the values there, by comparing same words. The profile needs quite some revision to be in line with Ratliff2010, however, and this is cool: Ratliff uses abstract tone categories, so they can also be inferred now and added.

If needed, I can also do this, @MacyL, in case you do not know how to advance.

**Comment by Wu-Urbanek** [comment]
ok, then I close this PR for now. Thanks for the suggestions

**Pull request closed without merging**
